apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-api
spec:
  selector:
    matchLabels:
      app: grpc-api
  replicas: 7
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-api
    spec:
      containers:
        - name: grpc-api
          image: gcr.io/locust-rest-grpc/locust-rest-grpc
          command: [ "python", "apis/grpc/grpc_server.py"]
#          imagePullPolicy: Never
          resources:
            requests:
              memory: 0.2G
              cpu: 1
            limits:
              memory: 2G
              cpu: 2
          ports:
            - name: grpc-api
              containerPort: 50051
          env:
            - name: MAX_WORKERS
              value: "1"
#      nodeSelector:
#        workload: api
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-api
spec:
  selector:
    app: grpc-api
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc-api
